# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180201_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
